fix(cronjob): ensure installation of jq

diff --git a/kubernetes/apps/productivity/paperless/app/jobs.yaml b/kubernetes/apps/productivity/paperless/app/jobs.yaml
--- a/kubernetes/apps/productivity/paperless/app/jobs.yaml
+++ b/kubernetes/apps/productivity/paperless/app/jobs.yaml
@@ -116,6 +116,12 @@ spec:
                   SMTP_PORT="25"
 
                   # Install required packages if missing
+
+                  if ! command -v jq > /dev/null; then
+                      echo "⚠️ jq is missing. Installing jq..."
+                      apk add --no-cache jq
+                  fi
+
                   for package in poppler-utils mailx jq; do
                       if ! command -v ${package%%-*} > /dev/null; then
                           echo "⚠️ $package is missing. Installing..."
